import Head from "next/head";
import Image from "next/image";
import { Container, Row, Col } from "react-bootstrap";
import styles from "@/styles/Home.module.scss";
import Calificacion from "@/components/Funcionality/Calificacion/Calificacion";
import TextoImagen from "@/components/Main/TextoImagen/TextoImagen";
import Slider from "@/components/Main/Slider/Slider";
import PricingCard from "@/components/Main/PricingCard/PricingCard";
import ImageComponent from "@/components/Main/ImageComponent/ImageComponent";
//import styles from '../components/Main/TextoImagen/TextoImagen.module.scss'

export default function Home() {
  const slides = [
    {
      imageUrl: "/images/Cover1.jpg",
      title: "",
      description: "",
    },
    {
      imageUrl: "/images/Cover2.jpg",
      title: "",
      description: "",
    },
    {
      imageUrl: "/images/TitlePL.png",
      title: "",
      description: "",
    },
  ];

  return (
    <>
      <Head>
        <title>Web template</title>
        <meta name="description" content="Generated by Anvetcorp" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Slider slides={slides} />
        <TextoImagen
          ladoTexto="derecha"
          titulo="Información"
          texto="Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint beatae ab maxime nulla
          architecto consequuntur neque ex repudiandae corporis cumque eius ratione possimus
          iusto magni quibusdam incidunt earum assumenda et necessitatibus iste amet, vel vero
          inventore. Corporis minus, aut perspiciatis nemo natus eius sed laboriosam error
          voluptatibus qui possimus voluptas."
          imageUrl="/images/certificado-mascota-sana.jpg"
          className={`${styles.textoImagenComponent1}`}
        />
        <TextoImagen
          ladoTexto="izquierda"
          titulo="Curso digital"
          texto="Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint beatae ab maxime nulla
          architecto consequuntur neque ex repudiandae corporis cumque eius ratione possimus
          iusto magni quibusdam incidunt earum assumenda et necessitatibus iste amet, vel vero
          inventore. Corporis minus, aut perspiciatis nemo natus eius sed laboriosam error
          voluptatibus qui possimus voluptas."
          imageUrl="/images/certificado-mascota-sana.jpg"
          //className={`${styles.textoImagenComponent}`}
        />
        <Row className={styles.calificacionRow}>
          <Col>
            <ImageComponent
              src="/images/certificado-mascota-sana.jpg"
              alt="Descripción de la imagen"
              width={500} // Estos valores son utilizados por `Image` para optimizar el espacio reservado antes de cargar la imagen
              height={300}
              colProps={{ xs: 12, md: 6, lg: 4 }} // Ocupa toda la fila en móviles, la mitad en tablets y un tercio en pantallas grandes
            />
            <Calificacion />

          </Col>
          <Col>
          <ImageComponent
              src="/images/certificado-mascota-sana.jpg"
              alt="Descripción de la imagen"
              width={500} // Estos valores son utilizados por `Image` para optimizar el espacio reservado antes de cargar la imagen
              height={300}
              colProps={{ xs: 12, md: 6, lg: 4 }} // Ocupa toda la fila en móviles, la mitad en tablets y un tercio en pantallas grandes
            />
            <Calificacion />
          </Col>
        </Row>

        <section id="Pricing" className={styles.pricingSection}>
          <h2 className={styles.pricingTitle}>Precios</h2>
          <Row className={styles.pricingCards}>
            <Col md={4} sm={12}>
              <PricingCard
                planName="Premium"
                price={200}
                period="mes"
                features={["Acceso a todas las clases", "Certificado de finalización"]}
                buttonText="Comprar"
                buttonAction={() => {
                  alert("Comprando el plan premium");
                }}
              />
            </Col>
            <Col md={4} sm={12}>
              <PricingCard
                planName="Básico"
                price={100}
                period="mes"
                features={["Acceso a 10 clases", "Certificado de finalización"]}
                buttonText="Comprar"
                buttonAction={() => {
                  alert("Comprando el plan básico");
                }}
              />
            </Col>
            <Col md={4} sm={12}>
              <PricingCard
                planName="Premium"
                price={200}
                period="mes"
                features={["Acceso a todas las clases", "Certificado de finalización"]}
                buttonText="Comprar"
                buttonAction={() => {
                  alert("Comprando el plan premium");
                }}
              />
            </Col>
          </Row>
        </section>
      </main>
    </>
  );
}
